Update workflow.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,12 +2,12 @@ name: CI
 on:
   push:
     branches:
-      - '*'
+      - '**'
     tags:
-      - '!*'
+      - '!**'
   pull_request:
     branches:
-      - '*'
+      - '**'
 jobs:
   test:
     strategy:
@@ -15,17 +15,43 @@ jobs:
         os:
           - ubuntu-latest
           - macOS-latest
-        swift_compat_ver:
+        swift-compat-ver:
           - '5'
           - '4.2'
           - '4'
     runs-on: ${{ matrix.os }}
     steps:
+    - uses: actions/checkout@v2
+    - name: Use a cache for ".build" directory.
+      uses: actions/cache@v1
+      with:
+        path: .build
+        key: build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-${{ hashFiles('Package.*') }}-${{ hashFiles('Sources/**/*.swift') }}
+        restore-keys: |
+          build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-${{ hashFiles('Package.*') }}-
+          build-${{ github.workspace }}-${{ runner.os }}-${{ matrix.swift-compat-ver }}-
+          build-${{ github.workspace }}-${{ runner.os }}-
+          build-${{ github.workspace }}-
     - uses: YOCKOW/Action-setup-swift@master
       with:
-        swift-version: '5.1'
-    - uses: actions/checkout@v1
+        swift-version: '5.2'
+    - name: Try to build products with debug mode.
+      run: |
+        swift build --configuration debug -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
+        if [ $? != 0 ]; then
+          echo "Failed to build products with debug mode."
+          rm -rf $(cd .build/debug && pwd -P)
+        fi
+      continue-on-error: true
     - name: Test with debug mode.
-      run: swift test --configuration debug -Xswiftc -swift-version -Xswiftc ${{ matrix.swift_compat_ver }}
+      run: swift test --configuration debug -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
+    - name: Try to build products with release mode.
+      run: |
+        swift build --configuration release -Xswiftc -enable-testing -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
+        if [ $? != 0 ]; then
+          echo "Failed to build products with release mode."
+          rm -rf $(cd .build/release && pwd -P)
+        fi
+      continue-on-error: true
     - name: Test with release mode.
-      run: swift test --configuration release -Xswiftc -enable-testing -Xswiftc -swift-version -Xswiftc ${{ matrix.swift_compat_ver }}
+      run: swift test --configuration release -Xswiftc -enable-testing -Xswiftc -swift-version -Xswiftc ${{ matrix.swift-compat-ver }}
